class ExpenseCategories {
  static const List<String> list = [
    'Food & Dining',
    'Groceries',
    'Rent',
    'Utilities',
    'Internet & Mobile',
    'Electricity',
    'Water',
    'Gas',
    'Transport',
    'Fuel',
    'Vehicle Maintenance',
    'Travel',
    'Shopping',
    'Clothing',
    'Electronics',
    'Personal Care',
    'Beauty & Grooming',
    'Entertainment',
    'Movies & OTT',
    'Gaming',
    'Healthcare',
    'Medicines',
    'Insurance',
    'Education',
    'Subscriptions',
    'Gifts & Donations',
    'Kids',
    'Pets',
    'Taxes',
    'Others',
  ];
}

class IncomeCategories {
  static const List<String> list = [
    'Salary',
    'Business Income',
    'Freelance',
    'Consulting',
    'Bonus',
    'Commission',
    'Interest',
    'Dividends',
    'Investment Returns',
    'Rental Income',
    'Pension',
    'Scholarship',
    'Government Benefits',
    'Refund',
    'Cashback',
    'Gift Received',
    'Side Hustle',
    'Royalties',
    'Selling Assets',
    'Other Income',
  ];
}
