
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2UWsW0y2KtmmKtVzmfECFqcO7QBfTny4',
    appId: '1:918046690152:web:8eb52106c1145d1e11a4dd',
    messagingSenderId: '918046690152',
    projectId: 'nova-f9f8b',
    authDomain: 'nova-f9f8b.firebaseapp.com',
    storageBucket: 'nova-f9f8b.firebasestorage.app',
    measurementId: 'G-75C6K027GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhqqje8X3dUUBvmnCmMqeFWSgwq_-_xac',
    appId: '1:918046690152:android:495049afb7c766aa11a4dd',
    messagingSenderId: '918046690152',
    projectId: 'nova-f9f8b',
    storageBucket: 'nova-f9f8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBczqmfR2QBekXOh56COj3NO3Rrs8mQ5vQ',
    appId: '1:918046690152:ios:49cd4f71ca354e5111a4dd',
    messagingSenderId: '918046690152',
    projectId: 'nova-f9f8b',
    storageBucket: 'nova-f9f8b.firebasestorage.app',
    iosBundleId: 'com.example.nova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBczqmfR2QBekXOh56COj3NO3Rrs8mQ5vQ',
    appId: '1:918046690152:ios:49cd4f71ca354e5111a4dd',
    messagingSenderId: '918046690152',
    projectId: 'nova-f9f8b',
    storageBucket: 'nova-f9f8b.firebasestorage.app',
    iosBundleId: 'com.example.nova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2UWsW0y2KtmmKtVzmfECFqcO7QBfTny4',
    appId: '1:918046690152:web:af94e03ada85b6f411a4dd',
    messagingSenderId: '918046690152',
    projectId: 'nova-f9f8b',
    authDomain: 'nova-f9f8b.firebaseapp.com',
    storageBucket: 'nova-f9f8b.firebasestorage.app',
    measurementId: 'G-33D2QDHMNT',
  );
}
